apiVersion: v1
kind: Service
metadata:
  name: streamlit-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8051
  selector:
    name: streamlit-app
status:
  loadBalancer: {}